model_name_or_path: <path to your base model>

### method
stage: pt
do_train: true
train_from_scratch: true # whether to use given params
finetuning_type: full
deepspeed: <path to LLaMA-Factory>/examples/deepspeed/ds_z3_config.json

### dataset
dataset: <path to your dataset>
cutoff_len: 1024
max_samples: 2000000
overwrite_cache: true
preprocessing_num_workers: 32

### output
output_dir: saves/<your run id>
logging_steps: 1
save_steps: 4000
save_only_model: true
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 5000

report_to: wandb
run_name: <your run id>